import { catchAsync } from "../utils/apiError";

export const isAuthenticated = catchAsync((req, res, next) => {});
